
spring:
  datasource:
    url: jdbc:mysql:///shop1903
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  registry:
    address: zookeeper://192.168.75.99:2181
  application:
    name: user_service
  protocol:
    port: -1
    name: dubbo
server:
  port: 9090
